-- Skema PostgreSQL, terjemahan dari database/schema.sql.
--
-- Tidak memuat CREATE DATABASE maupun USE: di Supabase basis datanya sudah ada
-- dan pemisahan dilakukan lewat schema, bukan basis data terpisah. Pemanggil
-- yang menentukan schema mana yang aktif lewat search_path.
--
-- Nilai status ditulis sebagai CHECK constraint, bukan tipe ENUM buatan.
-- ALTER TYPE ... ADD VALUE di PostgreSQL tidak bisa dibatalkan di dalam
-- transaksi, sedangkan CHECK constraint bisa diganti kapan saja. Daftar status
-- pengajuan di bawah wajib tetap cocok dengan StatusService::$allowedTransitions.

-- Pengganti ON UPDATE CURRENT_TIMESTAMP milik MySQL, yang tidak ada di
-- PostgreSQL. Dipasang sebagai trigger pada tabel yang punya updated_at.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $fn$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

-- 1. users
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('mahasiswa', 'sekretariat', 'admin')),
    status VARCHAR(20) DEFAULT 'aktif' CHECK (status IN ('aktif', 'nonaktif')),
    reset_token VARCHAR(64) NULL,
    reset_token_expires TIMESTAMPTZ NULL,
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_users_role_status ON users (role, status);
CREATE OR REPLACE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. mahasiswa_profiles
CREATE TABLE IF NOT EXISTS mahasiswa_profiles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    nim VARCHAR(50) NOT NULL,
    tempat_lahir VARCHAR(100),
    tanggal_lahir DATE,
    universitas VARCHAR(150) NOT NULL,
    fakultas VARCHAR(150),
    program_studi VARCHAR(150) NOT NULL,
    semester INT,
    nomor_hp VARCHAR(20),
    alamat TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. divisi
CREATE TABLE IF NOT EXISTS divisi (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_divisi VARCHAR(100) NOT NULL,
    deskripsi TEXT,
    kapasitas INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'aktif' CHECK (status IN ('aktif', 'nonaktif'))
);

-- 4. pengajuan
CREATE TABLE IF NOT EXISTS pengajuan (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_pengajuan VARCHAR(50) NOT NULL UNIQUE,
    user_id INT NOT NULL,
    divisi_id_preferensi INT,
    divisi_id_tawaran INT NULL,
    divisi_id_final INT NULL,
    tanggal_mulai_rencana DATE NOT NULL,
    tanggal_selesai_rencana DATE NOT NULL,
    tanggal_mulai_aktual DATE NULL,
    tanggal_selesai_aktual DATE NULL,
    status VARCHAR(40) DEFAULT 'draft' CHECK (status IN (
        'draft', 'diajukan', 'dalam_verifikasi', 'revisi',
        'menunggu_konfirmasi_tawaran', 'menunggu_finalisasi_sekretariat',
        'diterima', 'ditolak', 'dibatalkan_oleh_mahasiswa',
        'sedang_magang', 'selesai', 'mengundurkan_diri'
    )),
    alasan_penolakan TEXT NULL,
    catatan_verifikasi TEXT NULL,
    pembina_lapangan VARCHAR(150) NULL,
    diputuskan_oleh INT NULL,
    diputuskan_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (divisi_id_preferensi) REFERENCES divisi(id) ON DELETE SET NULL,
    FOREIGN KEY (divisi_id_tawaran) REFERENCES divisi(id) ON DELETE SET NULL,
    FOREIGN KEY (divisi_id_final) REFERENCES divisi(id) ON DELETE SET NULL,
    FOREIGN KEY (diputuskan_oleh) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_pengajuan_status ON pengajuan (status);
CREATE INDEX IF NOT EXISTS idx_pengajuan_dibuat ON pengajuan (created_at);
CREATE INDEX IF NOT EXISTS idx_pengajuan_user_status ON pengajuan (user_id, status);
CREATE OR REPLACE TRIGGER pengajuan_set_updated_at
    BEFORE UPDATE ON pengajuan FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 5. dokumen
CREATE TABLE IF NOT EXISTS dokumen (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pengajuan_id INT NOT NULL,
    jenis_dokumen VARCHAR(100) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    version INT DEFAULT 1,
    is_current BOOLEAN DEFAULT TRUE,
    uploaded_by INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pengajuan_id) REFERENCES pengajuan(id) ON DELETE CASCADE,
    FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE OR REPLACE TRIGGER dokumen_set_updated_at
    BEFORE UPDATE ON dokumen FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 6. status_history
CREATE TABLE IF NOT EXISTS status_history (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pengajuan_id INT NOT NULL,
    status_awal VARCHAR(50) NOT NULL,
    status_baru VARCHAR(50) NOT NULL,
    changed_by INT NULL,
    catatan TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pengajuan_id) REFERENCES pengajuan(id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
);

-- 7. notifications
CREATE TABLE IF NOT EXISTS notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    pengajuan_id INT NULL,
    pesan TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (pengajuan_id) REFERENCES pengajuan(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_notif_user_baca ON notifications (user_id, is_read);

-- 8. login_attempts
CREATE TABLE IF NOT EXISTS login_attempts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    attempted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_email_waktu ON login_attempts (email, attempted_at);
CREATE INDEX IF NOT EXISTS idx_ip_waktu ON login_attempts (ip_address, attempted_at);

-- 9. audit_logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NULL,
    action VARCHAR(100) NOT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id INT NOT NULL,
    details TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_dibuat ON audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_entitas ON audit_logs (entity, entity_id);
